using UnityEngine;

[CreateAssetMenu(fileName = "BaseInventoryContainerProfile", menuName = "Creatable/New BaseInventoryContainerProfile")]
public class BaseInventoryContainerProfile : ScriptableObject
{
    [SerializeField]
    [TextArea(3, 5)]
    protected string m_containerName;
    /// <summary>
    ///     Название контейнера для предметов
    /// </summary>
    public string ContainerName => m_containerName;


    [SerializeField]
    protected Sprite m_containerSprite;
    /// <summary>
    ///     Изображение контейнера 
    /// </summary>
    public Sprite ContainerSprite => m_containerSprite;


    [SerializeField]
    [TextArea(5, 10)]
    protected string m_containerDescription;
    /// <summary>
    ///     Описание контейнера для предметов
    /// </summary>
    public string ContainerDescription => m_containerDescription;


    [SerializeField]
    private bool m_useAutoGeneratedDescription = true;


    [SerializeField]
    private int m_containerCapacity;
    /// <summary>
    ///     Максимальная вместимость контейнера для предметов в слотах
    /// </summary>
    public int ContainerCapacity => m_containerCapacity;


    private void OnValidate()
    {
        AutoGenerateDescription();
    }

    private void AutoGenerateDescription()
    {
        if (m_useAutoGeneratedDescription)
        {
            m_containerDescription = $"'{m_containerName}' вмещает в себя '{m_containerCapacity}' ед. предметов";
        }
    }
}
